### ISSUE TITLE
Think of a better name

### ISSUE THREAD

**Issue by ScottRobbins** [SwiftBuildTools/Changes#5]
"ChangelogManager" isn't ideal for the name because the intent is that it will be able to be used for much more than managing a single Changelog. 

Also typing `Changelog-manager` in the command line is super annoying. Something that's just one word would be nice for a tool that will be frequently used.

**Comment by ScottRobbins** [comment]
I did shorten the executable's name to `changelog` to make that part easy to type. Idk still if this is the best name for the utility but any shorter names than that can likely be aliases (I could provide instructions for people to add an alias and call it `change` or something like that. 

One problem still with the name is that tab to complete (at least for `swift run cha` will tab to `swift run CHANGELOG.md`...which is not ideal.

**Comment by ScottRobbins** [comment]
Name ideas:
* `ChangelogManager` with executable named `changelog`
  * This one is still kind of annoying to type, and still doesn't reflect the larger features of the tool
* `Changes` with executable named `changes`
  * `Changes` is a pretty generic name, I could imagine there being types named `Changes`, but I think the compiler can figure that out.
  * `Changes` with the framework named `ChangesFramework`, and executable `changes`. longer import name but reduces type clashes. But it's kind of ugly.

**Comment by ScottRobbins** [comment]
Going with `Changes` as the name.

 I will make the executable named `changes`. The executable target `ChangesCLI`, and in the future the framework will be the target `Changes`.

**Comment by tuxagon** [comment]
Pls repoen

**Comment by ScottRobbins** [comment]
+1

**Comment by ScottRobbins** [comment]
Pretend bot message: Closed due to inactivity
